# Generated by Django 3.1.5 on 2021-03-10 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=255)),
                ('lname', models.CharField(max_length=255, null=True)),
                ('email', models.CharField(max_length=255)),
                ('fday', models.CharField(max_length=255)),
                ('desc', models.TextField(null=True)),
                ('active', models.BooleanField(default=False)),
                ('user_level', models.IntegerField()),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('delete_at', models.CharField(max_length=255, null=True)),
                ('password', models.CharField(max_length=255)),
            ],
        ),
    ]
