# Generated by Django 3.1.5 on 2021-03-10 20:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('session_register_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Messages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('user_msg', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='session_register_app.users')),
                ('who_sent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='msg_sent', to='session_register_app.users')),
            ],
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(max_length=255)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('message_com', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='user_app.messages')),
                ('who_comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='msg_commenteds', to='session_register_app.users')),
            ],
        ),
    ]
